apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway-api-crds.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.16.1
    includeCRDs: true
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml

