apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shawlz/argocd-example-apps.git
    targetRevision: HEAD
    path: app-of-apps/overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
