apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        environment: dev
      - cluster: in-cluster
        environment: staging
      - cluster: in-cluster
        environment: production
  template:
    metadata:
      name: 'base-{{.environment}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/shawlz/argocd-example-apps.git
        targetRevision: HEAD
        path: app-of-apps/overlays/{{.environment}}
      destination:
        name: '{{.cluster}}'
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 30s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
          