apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        namespace: dev
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        namespace: staging
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        namespace: production
  template:
    metadata:
      name: '{{.namespace}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/shawlz/argocd-example-apps.git
        targetRevision: HEAD
        path: kustomize-guestbook
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          